# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/parents/
    exclude:
      - sdk/parents/azure-arm-parent/pom.xml
      - sdk/parents/azure-client-sdk-parent/pom.xml
      - sdk/parents/azure-data-sdk-parent/pom.xml
      - sdk/parents/azure-sdk-parent/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/parents/
    exclude:
      - sdk/parents/azure-arm-parent/pom.xml
      - sdk/parents/azure-client-sdk-parent/pom.xml
      - sdk/parents/azure-data-sdk-parent/pom.xml
      - sdk/parents/azure-sdk-parent/pom.xml

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-pom-only.yml
  parameters:
    ServiceDirectory: parents
    Artifacts:
      - name: azure-client-sdk-parent
        groupId: com.azure
        safeName: azureclientsdkparent
      - name: azure-data-sdk-parent
        groupId: com.azure
        safeName: azuredatasdkparent
      - name: azure-sdk-parent
        groupId: com.azure
        safeName: azuresdkparent
