# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/boms/
    exclude:
      - sdk/boms/pom.xml
      - sdk/boms/azure-sdk-bom/pom.xml
      - sdk/boms/azure-sdk-template-bom/pom.xml
      - sdk/boms/azure-spring-boot-bom/pom.xml
      - sdk/boms/azure-spring-cloud-dependencies/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/boms/
    exclude:
      - sdk/boms/pom.xml
      - sdk/boms/azure-sdk-bom/pom.xml
      - sdk/boms/azure-sdk-template-bom/pom.xml
      - sdk/boms/azure-spring-boot-bom/pom.xml
      - sdk/boms/azure-spring-cloud-dependencies/pom.xml

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-pom-only.yml
  parameters:
    ServiceDirectory: boms
    Artifacts:
      - name: azure-sdk-bom
        groupId: com.azure
        safeName: azuresdkbom
      - name: azure-spring-boot-bom
        groupID: com.azure.spring
        safeName: azurespringbootbom
      - name: azure-spring-cloud-dependencies
        groupID: com.azure.spring
        safeName: azurespringclouddependencies
      - name: azure-sdk-template-bom
        groupID: com.azure
        safeName: azuresdktemplatebom
