# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/core/
    exclude:
      - sdk/core/pom.xml
      - sdk/core/azure-core/pom.xml
      - sdk/core/azure-core-amqp/pom.xml
      - sdk/core/azure-core-amqp-experimental/pom.xml
      - sdk/core/azure-core-experimental/pom.xml
      - sdk/core/azure-core-http-jdk-httpclient/pom.xml
      - sdk/core/azure-core-http-netty/pom.xml
      - sdk/core/azure-core-http-okhttp/pom.xml
      - sdk/core/azure-core-management/pom.xml
      - sdk/core/azure-core-serializer-avro-apache/pom.xml
      - sdk/core/azure-core-serializer-avro-jackson/pom.xml
      - sdk/core/azure-core-serializer-json-gson/pom.xml
      - sdk/core/azure-core-serializer-json-jackson/pom.xml
      - sdk/core/azure-core-test/pom.xml
      - sdk/core/azure-core-tracing-opentelemetry/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/core/
    exclude:
      - sdk/core/pom.xml
      - sdk/core/azure-core/pom.xml
      - sdk/core/azure-core-amqp/pom.xml
      - sdk/core/azure-core-amqp-experimental/pom.xml
      - sdk/core/azure-core-experimental/pom.xml
      - sdk/core/azure-core-http-jdk-httpclient/pom.xml
      - sdk/core/azure-core-http-netty/pom.xml
      - sdk/core/azure-core-http-okhttp/pom.xml
      - sdk/core/azure-core-management/pom.xml
      - sdk/core/azure-core-serializer-avro-apache/pom.xml
      - sdk/core/azure-core-serializer-avro-jackson/pom.xml
      - sdk/core/azure-core-serializer-json-gson/pom.xml
      - sdk/core/azure-core-serializer-json-jackson/pom.xml
      - sdk/core/azure-core-test/pom.xml
      - sdk/core/azure-core-tracing-opentelemetry/pom.xml


extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: core
    Artifacts:
      - name: azure-core
        groupId: com.azure
        safeName: azurecore
      - name: azure-core-amqp
        groupId: com.azure
        safeName: azurecoreamqp
      - name: azure-core-amqp-experimental
        groupId: com.azure
        safeName: azurecoreamqpexperimental
      - name: azure-core-experimental
        groupId: com.azure
        safeName: azurecoreexperimental
      - name: azure-core-http-jdk-httpclient
        groupId: com.azure
        safeName: azurecorehttpjdkhttpclient
      - name: azure-core-http-netty
        groupId: com.azure
        safeName: azurecorehttpnetty
      - name: azure-core-http-okhttp
        groupId: com.azure
        safeName: azurecorehttpokhttp
      - name: azure-core-management
        groupId: com.azure
        safeName: azurecoremanagement
      - name: azure-core-serializer-avro-apache
        groupId: com.azure
        safeName: azurecoreserializeravroapache
      - name: azure-core-serializer-json-gson
        groupId: com.azure
        safeName: azurecoreserializerjsongson
      - name: azure-core-serializer-json-jackson
        groupId: com.azure
        safeName: azurecoreserializerjsonjackson
      - name: azure-core-test
        groupId: com.azure
        safeName: azurecoretest
      - name: azure-core-tracing-opentelemetry
        groupId: com.azure
        safeName: azurecoretracingopentelemetry
    AdditionalModules:
      - name: perf-test-core
        groupId: com.azure
